cars = [
    {"Make" : "Audi",
    "Model" : "A7",
    "Year" : 2017,
    "Color" : "Red",
    "Price" : 66000,
    "Type" : "Gasoil"},

    {"Make" : "Audi",
    "Model" : "Q7",
    "Year" : 2017,
    "Color" : "Grey",
    "Price" : 65000,
    "Type" : "Gasoil"},

    {"Make" : "Ford",
    "Model" : "Mustang",
    "Year" : 2017,
    "Color" : "White",
    "Price" : 45000,
    "Type" : "Gasoline"},

    {"Make" : "Ford",
    "Model" : "Focus RS",
    "Year" : 2017,
    "Color" : "Blue",
    "Price" : 40000,
    "Type" : "Gasoline"},

    {"Make" : "Tesla",
    "Model" : "S",
    "Year" : 2017,
    "Color" : "Deep Blue",
    "Price" : 85000,
    "Type" : "Electric"},

    {"Make" : "Tesla",
    "Model" : "X",
    "Year" : 2017,
    "Color" : "White",
    "Price" : 97000,
    "Type" : "Electric"},

    {"Make" : "Volkswagen",
    "Model" : "Passat GTE",
    "Year" : 2017,
    "Color" : "Grey",
    "Price" : 48000,
    "Type" : "Electric"},

    {"Make" : "Volkswagen",
    "Model" : "Golf GTE",
    "Year" : 2017,
    "Color" : "Dark Iron",
    "Price" : 40000,
    "Type" : "Electric"},
]